<?php

namespace Database\Seeders;

use App\Models\Departement;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DepartementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $departements = [
            ['lib_departement' => 'Ain', 'code' => '01', 'region_id' => 1],
            ['lib_departement' => 'Aisne', 'code' => '02', 'region_id' => 7],
            ['lib_departement' => 'Allier', 'code' => '03', 'region_id' => 1],
            ['lib_departement' => 'Alpes-de-Haute-Provence', 'code' => '04', 'region_id' => 13],
            ['lib_departement' => 'Hautes-Alpes', 'code' => '05', 'region_id' => 13],
            ['lib_departement' => 'Alpes-Maritimes', 'code' => '06', 'region_id' => 13],
            ['lib_departement' => 'Ardèche', 'code' => '07', 'region_id' => 1],
            ['lib_departement' => 'Ardennes', 'code' => '08', 'region_id' => 6],
            ['lib_departement' => 'Ariège', 'code' => '09', 'region_id' => 11],
            ['lib_departement' => 'Aube', 'code' => '10', 'region_id' => 6],
            ['lib_departement' => 'Aude', 'code' => '11', 'region_id' => 11],
            ['lib_departement' => 'Aveyron', 'code' => '12', 'region_id' => 11],
            ['lib_departement' => 'Bouches-du-Rhône', 'code' => '13', 'region_id' => 13],
            ['lib_departement' => 'Calvados', 'code' => '14', 'region_id' => 9],
            ['lib_departement' => 'Cantal', 'code' => '15', 'region_id' => 1],
            ['lib_departement' => 'Charente', 'code' => '16', 'region_id' => 10],
            ['lib_departement' => 'Charente-Maritime', 'code' => '17', 'region_id' => 10],
            ['lib_departement' => 'Cher', 'code' => '18', 'region_id' => 4],
            ['lib_departement' => 'Corrèze', 'code' => '19', 'region_id' => 10],
            ['lib_departement' => 'Corse-du-Sud', 'code' => '2A', 'region_id' => 5],
            ['lib_departement' => 'Haute-Corse', 'code' => '2B', 'region_id' => 5],
            ['lib_departement' => 'Côte-d\'Or', 'code' => '21', 'region_id' => 2],
            ['lib_departement' => 'Côtes-d\'Armor', 'code' => '22', 'region_id' => 3],
            ['lib_departement' => 'Creuse', 'code' => '23', 'region_id' => 10],
            ['lib_departement' => 'Dordogne', 'code' => '24', 'region_id' => 10],
            ['lib_departement' => 'Doubs', 'code' => '25', 'region_id' => 2],
            ['lib_departement' => 'Drôme', 'code' => '26', 'region_id' => 1],
            ['lib_departement' => 'Eure', 'code' => '27', 'region_id' => 9],
            ['lib_departement' => 'Eure-et-Loir', 'code' => '28', 'region_id' => 4],
            ['lib_departement' => 'Finistère', 'code' => '29', 'region_id' => 3],
            ['lib_departement' => 'Gard', 'code' => '30', 'region_id' => 11],
            ['lib_departement' => 'Haute-Garonne', 'code' => '31', 'region_id' => 11],
            ['lib_departement' => 'Gers', 'code' => '32', 'region_id' => 11],
            ['lib_departement' => 'Gironde', 'code' => '33', 'region_id' => 10],
            ['lib_departement' => 'Hérault', 'code' => '34', 'region_id' => 11],
            ['lib_departement' => 'Ille-et-Vilaine', 'code' => '35', 'region_id' => 3],
            ['lib_departement' => 'Indre', 'code' => '36', 'region_id' => 4],
            ['lib_departement' => 'Indre-et-Loire', 'code' => '37', 'region_id' => 4],
            ['lib_departement' => 'Isère', 'code' => '38', 'region_id' => 1],
            ['lib_departement' => 'Jura', 'code' => '39', 'region_id' => 2],
            ['lib_departement' => 'Landes', 'code' => '40', 'region_id' => 10],
            ['lib_departement' => 'Loir-et-Cher', 'code' => '41', 'region_id' => 4],
            ['lib_departement' => 'Loire', 'code' => '42', 'region_id' => 1],
            ['lib_departement' => 'Haute-Loire', 'code' => '43', 'region_id' => 1],
            ['lib_departement' => 'Loire-Atlantique', 'code' => '44', 'region_id' => 12],
            ['lib_departement' => 'Loiret', 'code' => '45', 'region_id' => 4],
            ['lib_departement' => 'Lot', 'code' => '46', 'region_id' => 11],
            ['lib_departement' => 'Lot-et-Garonne', 'code' => '47', 'region_id' => 10],
            ['lib_departement' => 'Lozère', 'code' => '48', 'region_id' => 11],
            ['lib_departement' => 'Maine-et-Loire', 'code' => '49', 'region_id' => 12],
            ['lib_departement' => 'Manche', 'code' => '50', 'region_id' => 9],
            ['lib_departement' => 'Marne', 'code' => '51', 'region_id' => 6],
            ['lib_departement' => 'Haute-Marne', 'code' => '52', 'region_id' => 6],
            ['lib_departement' => 'Mayenne', 'code' => '53', 'region_id' => 12],
            ['lib_departement' => 'Meurthe-et-Moselle', 'code' => '54', 'region_id' => 6],
            ['lib_departement' => 'Meuse', 'code' => '55', 'region_id' => 6],
            ['lib_departement' => 'Morbihan', 'code' => '56', 'region_id' => 3],
            ['lib_departement' => 'Moselle', 'code' => '57', 'region_id' => 6],
            ['lib_departement' => 'Nièvre', 'code' => '58', 'region_id' => 2],
            ['lib_departement' => 'Nord', 'code' => '59', 'region_id' => 7],
            ['lib_departement' => 'Oise', 'code' => '60', 'region_id' => 7],
            ['lib_departement' => 'Orne', 'code' => '61', 'region_id' => 9],
            ['lib_departement' => 'Pas-de-Calais', 'code' => '62', 'region_id' => 7],
            ['lib_departement' => 'Puy-de-Dôme', 'code' => '63', 'region_id' => 1],
            ['lib_departement' => 'Pyrénées-Atlantiques', 'code' => '64', 'region_id' => 10],
            ['lib_departement' => 'Hautes-Pyrénées', 'code' => '65', 'region_id' => 11],
            ['lib_departement' => 'Pyrénées-Orientales', 'code' => '66', 'region_id' => 11],
            ['lib_departement' => 'Bas-Rhin', 'code' => '67', 'region_id' => 6],
            ['lib_departement' => 'Haut-Rhin', 'code' => '68', 'region_id' => 6],
            ['lib_departement' => 'Rhône', 'code' => '69', 'region_id' => 1],
            ['lib_departement' => 'Haute-Saône', 'code' => '70', 'region_id' => 2],
            ['lib_departement' => 'Saône-et-Loire', 'code' => '71', 'region_id' => 2],
            ['lib_departement' => 'Sarthe', 'code' => '72', 'region_id' => 12],
            ['lib_departement' => 'Savoie', 'code' => '73', 'region_id' => 1],
            ['lib_departement' => 'Haute-Savoie', 'code' => '74', 'region_id' => 1],
            ['lib_departement' => 'Paris', 'code' => '75', 'region_id' => 8],
            ['lib_departement' => 'Seine-Maritime', 'code' => '76', 'region_id' => 9],
            ['lib_departement' => 'Seine-et-Marne', 'code' => '77', 'region_id' => 8],
            ['lib_departement' => 'Yvelines', 'code' => '78', 'region_id' => 8],
            ['lib_departement' => 'Deux-Sèvres', 'code' => '79', 'region_id' => 10],
            ['lib_departement' => 'Somme', 'code' => '80', 'region_id' => 7],
            ['lib_departement' => 'Tarn', 'code' => '81', 'region_id' => 11],
            ['lib_departement' => 'Tarn-et-Garonne', 'code' => '82', 'region_id' => 11],
            ['lib_departement' => 'Var', 'code' => '83', 'region_id' => 13],
            ['lib_departement' => 'Vaucluse', 'code' => '84', 'region_id' => 13],
            ['lib_departement' => 'Vendée', 'code' => '85', 'region_id' => 12],
            ['lib_departement' => 'Vienne', 'code' => '86', 'region_id' => 10],
            ['lib_departement' => 'Haute-Vienne', 'code' => '87', 'region_id' => 10],
            ['lib_departement' => 'Vosges', 'code' => '88', 'region_id' => 6],
            ['lib_departement' => 'Yonne', 'code' => '89', 'region_id' => 2],
            ['lib_departement' => 'Territoire de Belfort', 'code' => '90', 'region_id' => 2],
            ['lib_departement' => 'Essonne', 'code' => '91', 'region_id' => 8],
            ['lib_departement' => 'Hauts-de-Seine', 'code' => '92', 'region_id' => 8],
            ['lib_departement' => 'Seine-Saint-Denis', 'code' => '93', 'region_id' => 8],
            ['lib_departement' => 'Val-de-Marne', 'code' => '94', 'region_id' => 8],
            ['lib_departement' => 'Val-d\'Oise', 'code' => '95', 'region_id' => 8],
            ['lib_departement' => 'Guadeloupe', 'code' => '971', 'region_id' => 14],
            ['lib_departement' => 'Martinique', 'code' => '972', 'region_id' => 15],
            ['lib_departement' => 'Guyane', 'code' => '973', 'region_id' => 16],
            ['lib_departement' => 'La Réunion', 'code' => '974', 'region_id' => 17],
            ['lib_departement' => 'Mayotte', 'code' => '976', 'region_id' => 18],
        ];

        foreach ($departements as $departement) {
            Departement::create($departement);
        }
    }
}
